### ISSUE TITLE
Alternative to use-package :defer [N]

### ISSUE THREAD

**Issue by MunsterPlop** [conao3/leaf-keywords.el#125]
Hi,

I recently switched to leaf.el from use-package and so far I'm pretty happy with it.
The only thing I'm missing from use-package is the `:defer [N]` feature that I used pretty extensively to defer loading a package n amount of seconds.
From what I saw in the use-package source, it should be pretty straight forward to implement using `(run-with-idle-timer)`.
Is there any plan for something like it?

**Comment by conao3** [comment]
The defer feature can make debugging difficult. If an idle Emacs suddenly gives an error, how do we handle it?
There is no use-package :defer in leaf. Instead, it acts as if every leaf has a pseudo use-package :defer.
If you have more concrete examples, I can make more concrete suggestions.

**Comment by MunsterPlop** [comment]
I am not proficient enough in elisp so I'm not sure about how you'd handle errors  like that. To be honest I haven't really faced that but I can see how it could be a problem.
As an example of my use case,
I tend to defer loading some packages that I don't need to load during startup but that I will need after it's done. I use it with quite a few builtins like winner-mode, windmove, auto revert... etc and accumulated, it does make a difference in startup time.
I'm not the only one and I have also seen quite a few people using defer n with ivy and projectile.
For some of these, you could probably use :hook or :commands but it does feel better when the package load doesn't impact calls to counsel-M-x or projectile-mode-map or even file openings.

**Comment by conao3** [comment]
I understand. After a few days of thinking, I have decided not to support this specification.
This is a project decision, not a technical one.
