### ISSUE TITLE
Support :pretty-hydra

### ISSUE THREAD

**Issue by MunsterPlop** [conao3/leaf-keywords.el#137]
Leaf already has `:hydra`.
Whynot also provide `:pretty-hydra` (https://github.com/jerrypnz/major-mode-hydra.el#pretty-hydra) ?
It is already available for use-package though I believe the functionality is provided by pretty-hydra itself and not use-package
so I'm not sure what would be the best solution here.
What do you think?

**Comment by conao3** [comment]
Thanks, add these keywords. Please read the documentation, and try it.

**Comment by MunsterPlop** [comment]
> 
> 
> Thanks, add these keywords. Please read the documentation, and try it.

I just tried it and so far, it works perfectly.
Thank you very much for your work.
