### ISSUE TITLE
Suppress flycheck unrecognized leaf-keywords errors.

### ISSUE THREAD

**Issue by minorugh** [conao3/leaf-keywords.el#154]
I love Leaf.el and was able to build a comfortable EMACS configuration file. Thank you very much.

The initialization file is split and loaded by init-loader.el, but when I set flycheck-mode for each split file, I get the following warning

```leaf: Unrecognized keyword :***```

`:hydra` `:el-get` `:chord` and so on.

However, these warnings can be suppressed by adding the following at the beginning of each split file
```
(eval-when-compile (leaf-keywords-init))
```
I am not sure if this is the right way to do it, so if there is a smarter way to suppress the warnings, please let me know.

**Comment by minorugh** [comment]
Thanks Naoya! for the clear explanation and advice.
I changed the flycheck settings as you indicated and it worked perfectly.

Byte-compilation of split files is performed at emacs exit, not in
real time.

```emacs-lisp
(defun auto-compile-inits ()
  "Byte compile Lisp files modified in the directory."
  (interactive)
  (byte-compile-file "~/.emacs.d/init.el")
  (byte-recompile-directory (expand-file-name "~/.emacs.d/elisp") 0)
  (byte-recompile-directory (expand-file-name "~/.emacs.d/inits") 0))
(add-hook 'kill-emacs-hook 'auto-compile-inits)
```

**Comment by conao3** [comment]
Is there any unclear points? If this issue is completed, I want to close this.

**Comment by minorugh** [comment]
I have had no problems at all since then. I have learnt a lot from this advice. I thank you from the bottom of my heart.
