### ISSUE TITLE
:combo keyword ignore first combo setting

### ISSUE THREAD

**Issue by yonta** [conao3/leaf-keywords.el#157]
The `:combo` keyword ignore first setting.

## minimal leaf-expand example

```elisp
(leaf key-combo
  :combo (("="   . (" = " " == " " === " ))
          ("=>"  . " => ")))

;; --------------------------------------------------------------------------------

(prog1 'key-combo
  (key-combo-define global-map "=>" " => "))
```

## environment

- Emacs 29.4
- leaf 20230803.729
- leaf-keywords 20240618.10

**Comment by conao3** [comment]
Confirmed; This behavior also described testcase.
https://github.com/conao3/leaf-keywords.el/blob/febda9969046019aae3bf3b7d1f042e9dbef2af9/leaf-keywords-tests.el#L587-L607

**Comment by conao3** [comment]
@yonta thanks reporting this! I have pushed patch, please try it

**Comment by yonta** [comment]
Thansk to fix!
