### ISSUE TITLE
Feature request: straight package manager support

### ISSUE THREAD

**Issue by leotaku** [conao3/leaf-keywords.el#33]
I noticed leaf already has el-get support through the `:el-get` keyword, however I prefer to use the [straight](https://github.com/raxod502/straight.el) package manager.

Would you be willing to add support for straight to leaf?

The straight's interface works as follows:
```elisp
;; fetch the "package-name" package from a set of predefined repos
(straight-use-package 'package-name)
;; fetch a package defined by a recipe
(straight-use-package '(package-name keywords))
```

If you want I can gladly open a PR myself, but with this being a pretty small addition you might just prefer to add it yourself to avoid future FSF licensing woes.

**Comment by conao3** [comment]
Ok. leaf-keyword depends on many many external packages, so leaf-keywords.el is not planned to merge ELPA or Emacs-core.
PR is welcome.

**Comment by conao3** [comment]
If you want to add ~:straight~ keyword, please also add testcases like ~:el-get~ keyword.

**Comment by leotaku** [comment]
Great! Is there anything non-obvious I should look out for? Also, what part of the code should generally go into the "normalize" and what into the "keywords" list?

**Comment by conao3** [comment]
You can reference `:el-get` normalizer in `leaf-normalize` and keyword handler in `leaf-keywords`.
https://github.com/conao3/leaf-keywords.el/blob/4c048cbc8120976dda7bae1080e9d35da5072930/leaf-keywords.el#L326-L330
https://github.com/conao3/leaf-keywords.el/blob/4c048cbc8120976dda7bae1080e9d35da5072930/leaf-keywords.el#L112-L114

After being fully normalized, generate the necessary few lines of S expression by `mapcar`.
If you need a lot of S expressions each symbol, prepare a macro like the `:ensure` keyword.
https://github.com/conao3/leaf.el/blob/65a2e4cde21c109f070cb7b3fd0b3be69730f54e/leaf.el#L213
https://github.com/conao3/leaf.el/blob/65a2e4cde21c109f070cb7b3fd0b3be69730f54e/leaf.el#L541-L560

**Comment by conao3** [comment]
This issue solved by the feature added 🎉
